import sys

with open(sys.argv[1], 'r') as f:
    lines = f.readlines()

meetings_start = -1
for i, line in enumerate(lines):
    if "activeTab === 'meetings'" in line:
        meetings_start = i
        break

if meetings_start != -1:
    new_content_block = [
        '                        {contentView === "kanban" && (\n',
        '                           <div className="flex gap-8 overflow-x-auto pb-10 no-scrollbar">\n',
        '                              {Object.entries(statusConfig).map(([status, config]) => (\n',
        '                                 <div key={status} className="flex-shrink-0 w-[400px] space-y-6">\n',
        '                                    <div className="flex items-center justify-between px-4">\n',
        '                                       <div className="flex items-center gap-3">\n',
        '                                          <div className={`w-3 h-3 rounded-full ${config.dot} shadow-sm shadow-black/5`}/>\n',
        '                                          <h4 className="text-sm font-black text-[#0F172A] uppercase tracking-widest">{config.label}</h4>\n',
        '                                       </div>\n',
        '                                       <span className="text-[10px] font-black text-slate-300 bg-slate-100 px-3 py-1.5 rounded-xl">\n',
        '                                         {filteredPlans.filter(p => p.status === status).length}\n',
        '                                       </span>\n',
        '                                    </div>\n',
        '                                    \n',
        '                                    <div className="space-y-4 min-h-[400px]">\n',
        '                                       {filteredPlans.filter(p => p.status === status).map((plan) => (\n',
        '                                          <Card key={plan.id} className="p-6 bg-white border border-slate-100 shadow-lg shadow-slate-200/50 rounded-3xl space-y-4 hover:border-emerald-200 transition-all cursor-grab active:cursor-grabbing">\n',
        '                                             <div className="flex items-center justify-between">\n',
        '                                                <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{plan.platform}</span>\n',
        '                                                <span className="text-[9px] font-black text-emerald-600 bg-emerald-50 px-2 py-1 rounded-md">{plan.content_pillar || "Default"}</span>\n',
        '                                             </div>\n',
        '                                             <h5 className="text-sm font-black text-[#0F172A] leading-snug">{plan.headline || plan.title}</h5>\n',
        '                                             <div className="flex items-center justify-between pt-4 border-t border-slate-50">\n',
        '                                                 <div className="flex items-center gap-2"> \n',
        '                                                    <div className="w-5 h-5 rounded-full bg-slate-50 border border-slate-200 overflow-hidden shadow-sm"> \n',
        '                                                       <img \n',
        '                                                          src={plan.creator?.avatar_url || (currentUserProfile?.avatar_url || `https://api.dicebear.com/7.x/initials/svg?seed=${plan.creator?.full_name || (currentUserProfile?.full_name || "Main Authority")}`)} \n',
        '                                                          className="w-full h-full object-contain p-0.5" \n',
        '                                                          alt="Creator" \n',
        '                                                       /> \n',
        '                                                    </div> \n',
        '                                                    <span className="text-[10px] font-bold text-slate-500 italic">{plan.creator?.full_name || (currentUserProfile?.full_name || "Main Authority")}</span> \n',
        '                                                 </div>\n',
        '                                                <span className="text-[9px] font-black text-slate-300 uppercase">{plan.due_date ? new Date(plan.due_date).toLocaleDateString() : "-"}</span>\n',
        '                                             </div>\n',
        '                                          </Card>\n',
        '                                       ))}\n',
        '                                    </div>\n',
        '                                 </div>\n',
        '                              ))}\n',
        '                           </div>\n',
        '                        )}\n',
        '\n',
        '                        {contentView === "calendar" && (() => {\n',
        '                          const year = currentCalendarDate.getFullYear();\n',
        '                          const month = currentCalendarDate.getMonth();\n',
        '                          const daysInMonth = new Date(year, month + 1, 0).getDate();\n',
        '                          const firstDayOfMonth = new Date(year, month, 1).getDay();\n',
        '                          const days = Array.from({ length: daysInMonth }, (_, i) => i + 1);\n',
        '                          const blanks = Array.from({ length: firstDayOfMonth }, (_, i) => i);\n',
        '\n',
        '                          return (\n',
        '                            <Card className="p-10 bg-white border-none shadow-2xl shadow-slate-200/40 rounded-[44px] space-y-8 animate-in fade-in zoom-in-95 duration-500">\n',
        '                              <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 px-2">\n',
        '                                <div className="flex items-center gap-5">\n',
        '                                  <div className="w-16 h-16 bg-emerald-50 text-emerald-600 rounded-3xl flex items-center justify-center shadow-inner">\n',
        '                                     <CalendarIcon size={32}/>\n',
        '                                  </div>\n',
        '                                  <div>\n',
        '                                    <h3 className="text-3xl font-black text-[#0F172A] tracking-tight">{monthNames[month]} {year}</h3>\n',
        '                                    <div className="flex items-center gap-2 mt-1">\n',
        '                                       <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"/>\n',
        '                                       <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">\n',
        '                                         {filteredPlans.filter(p => {\n',
        '                                           if (!p.due_date) return false;\n',
        '                                           const d = new Date(p.due_date);\n',
        '                                           return d.getMonth() === month && d.getFullYear() === year;\n',
        '                                         }).length} Tasks This Month\n',
        '                                       </p>\n',
        '                                    </div>\n',
        '                                  </div>\n',
        '                                </div>\n',
        '                                <div className="flex items-center gap-3 bg-slate-50 p-2 rounded-[24px] border border-slate-100/50">\n',
        '                                  <button \n',
        '                                    onClick={() => setCurrentCalendarDate(new Date(year, month - 1, 1))}\n',
        '                                    className="w-12 h-12 flex items-center justify-center bg-white hover:bg-emerald-50 text-slate-400 hover:text-emerald-600 rounded-2xl transition-all hover:scale-105 active:scale-95 shadow-sm"\n',
        '                                  >\n',
        '                                    <ChevronLeft size={20}/>\n',
        '                                  </button>\n',
        '                                  <button \n',
        '                                    onClick={() => setCurrentCalendarDate(new Date())}\n',
        '                                    className="px-6 py-3 bg-slate-900 text-white rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] shadow-xl shadow-slate-900/10 hover:scale-105 active:scale-95 transition-all"\n',
        '                                  >\n',
        '                                    Today\n',
        '                                  </button>\n',
        '                                  <button \n',
        '                                    onClick={() => setCurrentCalendarDate(new Date(year, month + 1, 1))}\n',
        '                                    className="w-12 h-12 flex items-center justify-center bg-white hover:bg-emerald-50 text-slate-400 hover:text-emerald-600 rounded-2xl transition-all hover:scale-105 active:scale-95 shadow-sm"\n',
        '                                  >\n',
        '                                    <ChevronRight size={20}/>\n',
        '                                  </button>\n',
        '                                </div>\n',
        '                              </div>\n',
        '\n',
        '                              <div className="grid grid-cols-7 gap-3">\n',
        '                                 {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(day => (\n',
        '                                    <div key={day} className="py-4 text-center text-[10px] font-black uppercase text-slate-300 tracking-[0.4em]">{day}</div>\n',
        '                                 ))}\n',
        '                                 {blanks.map(b => (\n',
        '                                    <div key={`blank-${b}`} className="min-h-[160px] rounded-[32px] bg-slate-50/20 border border-slate-50/30"></div>\n',
        '                                 ))}\n',
        '                                 {days.map(day => {\n',
        '                                    const plansOnThisDay = filteredPlans.filter(p => {\n',
        '                                       if (!p.due_date) return false;\n',
        '                                       const d = new Date(p.due_date);\n',
        '                                       return d.getDate() === day && d.getMonth() === month && d.getFullYear() === year;\n',
        '                                    });\n',
        '                                    const isToday = new Date().toDateString() === new Date(year, month, day).toDateString();\n',
        '\n',
        '                                    return (\n',
        '                                       <div key={day} className={`min-h-[160px] p-4 rounded-[32px] border transition-all group ${isToday ? "bg-emerald-50/30 border-emerald-100" : "border-slate-100/50 hover:bg-slate-50"}`}>\n',
        '                                          <div className="flex items-center justify-between mb-2">\n',
        '                                            <span className={`text-xs font-black ${isToday ? "w-8 h-8 rounded-full bg-emerald-600 text-white flex items-center justify-center shadow-lg shadow-emerald-500/20" : "text-slate-400"}`}>{day}</span>\n',
        '                                          </div>\n',
        '                                          <div className="space-y-2">\n',
        '                                             {plansOnThisDay.map(plan => (\n',
        '                                               <div key={plan.id} onClick={() => openEditModal(plan)} className="p-2 bg-white rounded-xl border border-slate-50 shadow-sm cursor-pointer hover:border-emerald-500 transition-all">\n',
        '                                                  <p className="text-[9px] font-black text-[#0F172A] line-clamp-1 truncate">{plan.headline || plan.title}</p>\n',
        '                                               </div>\n',
        '                                             ))}\n',
        '                                             {plansOnThisDay.length === 0 && (\n',
        '                                               <div className="opacity-0 group-hover:opacity-100 transition-opacity bg-slate-50/50 rounded-2xl p-3 flex items-center justify-center border border-dashed border-slate-200">\n',
        '                                                  <Plus size={12} className="text-slate-300"/>\n',
        '                                               </div>\n',
        '                                             )}\n',
        '                                          </div>\n',
        '                                       </div>\n',
        '                                    );\n',
        '                                 })}\n',
        '                              </div>\n',
        '                            </Card>\n',
        '                          );\n',
        '                        })()}\n',
        '                      </>\n',
        '                   );\n',
        '                })()}\n',
        '\n',
        '                {contentPlans.length === 0 && (\n',
        '                   <div className="py-40 text-center space-y-6 bg-white rounded-[44px] border border-slate-50 shadow-sm">\n',
        '                      <Layers size={60} className="mx-auto text-slate-100"/>\n',
        '                      <div className="space-y-2">\n',
        '                         <h3 className="text-xl font-black text-[#0F172A]">Belum Ada Antrean Konten</h3>\n',
        '                         <p className="text-slate-400 text-sm font-medium max-w-sm mx-auto italic">Mulai kolaborasi dengan menambahkan tugas konten pertama tim Anda.</p>\n',
        '                      </div>\n',
        '                   </div>\n',
        '                )}\n'
    ]

    table_end_idx = -1
    for i in range(1640, meetings_start):
        if i < len(lines) and '                    </Card>' in lines[i] and 'table' not in lines[i]:
            table_end_idx = i
            break
            
    if table_end_idx != -1:
        lines[table_end_idx+1:meetings_start] = new_content_block
    else:
        lines[1648:meetings_start] = new_content_block

with open(sys.argv[1], 'w') as f:
    f.writelines(lines)
