import sys

with open(sys.argv[1], 'r') as f:
    lines = f.readlines()

content_line_idx = -1
for i, line in enumerate(lines):
    if "activeTab === 'content'" in line:
        content_line_idx = i
        break

meetings_start = -1
for i, line in enumerate(lines):
    if "activeTab === 'meetings'" in line:
        meetings_start = i
        break

if content_line_idx != -1 and meetings_start != -1:
    # Rewrite the whole Content Tab block from the header onwards
    # This is safer than trying to patch the mess
    
    new_active_tab_content = [
        '           {activeTab === "content" && (\n',
        '              <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">\n',
        '                 <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">\n',
        '                    <div className="space-y-1">\n',
        '                       <h3 className="text-3xl font-black text-[#0F172A] italic">\n',
        '                          Content Production Line\n',
        '                          {selectedAccountId !== "all" && (\n',
        '                             <span className="text-emerald-500 ml-2">\n',
        '                                — {accounts.find(a => a.id === selectedAccountId)?.name}\n',
        '                             </span>\n',
        '                          )}\n',
        '                       </h3>\n',
        '                       <p className="text-slate-400 text-sm font-medium italic">Manage your content lifecycle from strategy to publishing.</p>\n',
        '                    </div>\n',
        '                    \n',
        '                    <div className="flex items-center gap-3 bg-slate-100/50 p-2 rounded-2xl border border-slate-100">\n',
        '                       {[\n',
        '                         { id: "table", icon: <Table2 size={16}/> },\n',
        '                         { id: "kanban", icon: <Kanban size={16}/> },\n',
        '                         { id: "calendar", icon: <CalendarIcon size={16}/> }\n',
        '                       ].map((v) => (\n',
        '                         <button \n',
        '                           key={v.id}\n',
        '                           onClick={() => setContentView(v.id as any)}\n',
        '                           className={`p-3 rounded-xl transition-all ${contentView === v.id ? "bg-white text-emerald-600 shadow-sm" : "text-slate-400 hover:text-slate-600"}`}\n',
        '                         >\n',
        '                           {v.icon}\n',
        '                         </button>\n',
        '                       ))}\n',
        '                       <div className="w-[1px] h-6 bg-slate-200 mx-1"/>\n',
        '                       <Button onClick={() => setIsTaskModalOpen(true)} className="bg-emerald-600 text-white h-11 px-6 rounded-xl font-bold text-xs">\n',
        '                         <Plus size={16} className="mr-2"/> New Content\n',
        '                       </Button>\n',
        '                    </div>\n',
        '                 </div>\n',
        '\n',
        '                 <div className="flex flex-wrap items-center gap-3">\n',
        '                    {["all", "tiktok", "instagram", "threads", "youtube", "facebook"].map(plat => (\n',
        '                       <button\n',
        '                         key={plat}\n',
        '                         onClick={() => setPlatformFilter(plat)}\n',
        '                         className={`px-5 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${platformFilter === plat ? "bg-emerald-600 text-white shadow-lg shadow-emerald-500/20" : "bg-white text-slate-400 hover:text-slate-600 border border-slate-100"}`}\n',
        '                       >\n',
        '                         {plat === "all" ? "All Platforms" : plat}\n',
        '                       </button>\n',
        '                    ))}\n',
        '                 </div>\n',
        '\n',
        '                 {(() => {\n',
        '                    const filteredPlans = contentPlans.filter(p => platformFilter === "all" || p.platform === platformFilter);\n',
        '\n',
        '                    return (\n',
        '                       <>\n',
        '                         {contentView === "table" && (\n',
        '                            <Card className="p-0 border-none shadow-xl shadow-slate-200/50 bg-white overflow-hidden rounded-[40px]">\n',
        '                               <div className="overflow-x-auto">\n',
        '                                  <table className="w-full">\n',
        '                                     <thead>\n',
        '                                        <tr className="bg-slate-50/50">\n',
        '                                           <th className="px-8 py-5 text-left text-[10px] font-black uppercase tracking-widest text-slate-400">Content / Pillar</th>\n',
        '                                           <th className="px-8 py-5 text-left text-[10px] font-black uppercase tracking-widest text-slate-400">Platform</th>\n',
        '                                           <th className="px-8 py-5 text-left text-[10px] font-black uppercase tracking-widest text-slate-400">Phase</th>\n',
        '                                           <th className="px-8 py-5 text-left text-[10px] font-black uppercase tracking-widest text-slate-400">PIC</th>\n',
        '                                           <th className="px-8 py-5 text-left text-[10px] font-black uppercase tracking-widest text-slate-400">Due Date</th>\n',
        '                                           <th className="px-8 py-5 text-left text-[10px] font-black uppercase tracking-widest text-slate-400">Assets</th>\n',
        '                                           <th className="px-8 py-5 text-left text-[10px] font-black uppercase tracking-widest text-slate-400">Live Link</th>\n',
        '                                           <th className="px-8 py-5 text-right text-[10px] font-black uppercase tracking-widest text-slate-400">Action</th>\n',
        '                                        </tr>\n',
        '                                     </thead>\n',
        '                                     <tbody>\n',
        '                                        {filteredPlans.map((plan) => (\n',
        '                                           <tr key={plan.id} className={`border-b border-slate-50 hover:bg-slate-50/30 transition-all relative ${plan.status === "approved" ? "bg-emerald-50/10" : ""}`}>\n',
        '                                              <td className="px-8 py-6 relative">\n',
        '                                                 {plan.status === "approved" && <div className="absolute left-0 top-0 bottom-0 w-1 bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.3)]"/>}\n',
        '                                                 <div className="space-y-1">\n',
        '                                                    <p className="text-sm font-black text-[#0F172A] flex items-center gap-2">\n',
        '                                                       {plan.headline || plan.title}\n',
        '                                                       {plan.status === "approved" && <ShieldCheck size={14} className="text-emerald-500 animate-pulse flex-shrink-0"/>}\n',
        '                                                    </p>\n',
        '                                                    <div className="flex items-center gap-2">\n',
        '                                                       <span className="text-[9px] font-black px-2 py-0.5 rounded bg-slate-100 text-slate-500 uppercase">{plan.content_pillar || "No Pillar"}</span>\n',
        '                                                    </div>\n',
        '                                                 </div>\n',
        '                                              </td>\n',
        '                                              <td className="px-8 py-6">\n',
        '                                                 <span className="text-[10px] font-black uppercase text-slate-400">{plan.platform}</span>\n',
        '                                              </td>\n',
        '                                              <td className="px-8 py-6">\n',
        '                                                  <select \n',
        '                                                    value={plan.status} \n',
        '                                                    onChange={(e) => handleUpdateTaskStatus(plan.id, e.target.value)} \n',
        '                                                    className={`px-3 py-1.5 rounded-lg text-[9px] font-black uppercase w-fit border outline-none cursor-pointer hover:scale-105 transition-all appearance-none text-center ${ \n',
        '                                                      statusConfig[plan.status]?.bg || "bg-slate-50"\n',
        '                                                    } ${ \n',
        '                                                      statusConfig[plan.status]?.color || "text-slate-600"\n',
        '                                                    } ${ \n',
        '                                                      statusConfig[plan.status]?.border || "border-slate-100"\n',
        '                                                    }`} \n',
        '                                                  > \n',
        '                                                    {Object.entries(statusConfig).map(([key, config]) => (\n',
        '                                                      <option key={key} value={key}>{config.label}</option>\n',
        '                                                    ))}\n',
        '                                                  </select>\n',
        '                                              </td>\n',
        '                                              <td className="px-8 py-6">\n',
        '                                                  {(() => {\n',
        '                                                     const pic = members.find(m => m.v2_profiles?.id === plan.assigned_to)?.v2_profiles;\n',
        '                                                     if (pic) {\n',
        '                                                        return (\n',
        '                                                           <div className="flex items-center gap-2 group/pic relative">\n',
        '                                                              <div className="w-7 h-7 rounded-full bg-slate-100 border border-white shadow-sm overflow-hidden shrink-0">\n',
        '                                                                 {pic.avatar_url ? (\n',
        '                                                                    <img src={pic.avatar_url} className="w-full h-full object-cover" />\n',
        '                                                                 ) : (\n',
        '                                                                    <div className="w-full h-full flex items-center justify-center text-[10px] font-black text-slate-400">\n',
        '                                                                       {pic.full_name?.[0] || \"U\"}\n',
        '                                                                    </div>\n',
        '                                                                 )}\n',
        '                                                              </div>\n',
        '                                                              <span className="text-[10px] font-bold text-slate-600 truncate max-w-[80px]">{pic.full_name}</span>\n',
        '                                                           </div>\n',
        '                                                        );\n',
        '                                                     }\n',
        '                                                     return <span className="text-[10px] font-bold text-slate-300 italic">Unassigned</span>;\n',
        '                                                  })()}\n',
        '                                               </td>\n',
        '                                              <td className="px-8 py-6 text-xs font-bold text-slate-600">\n',
        '                                                 {plan.due_date ? new Date(plan.due_date).toLocaleDateString() : "-"}\n',
        '                                              </td>\n',
        '                                              <td className="px-8 py-6">\n',
        '                                                 <div className="flex flex-wrap items-center gap-2">\n',
        '                                                    {plan.script_url && (\n',
        '                                                       <a href={plan.script_url} target="_blank" className="flex items-center gap-2 px-3 py-1.5 bg-slate-100 text-slate-600 rounded-lg hover:bg-slate-200 transition-all text-xs font-bold" title="Script">\n',
        '                                                          <FileText size={14}/>\n',
        '                                                          <span>Script</span>\n',
        '                                                       </a>\n',
        '                                                    )}\n',
        '                                                    {plan.result_url && (\n',
        '                                                       <a href={plan.result_url} target="_blank" className="flex items-center gap-2 px-3 py-1.5 bg-blue-50 text-blue-600 rounded-lg hover:bg-blue-100 transition-all text-xs font-bold" title="Result Content">\n',
        '                                                          <Video size={14}/>\n',
        '                                                          <span>Konten</span>\n',
        '                                                       </a>\n',
        '                                                    )}\n',
        '                                                    {!plan.script_url && !plan.result_url && <span className="text-[10px] text-slate-300 font-bold italic">No Assets</span>}\n',
        '                                                 </div>\n',
        '                                              </td>\n',
        '                                              <td className="px-8 py-6">\n',
        '                                                 <div className="flex items-center gap-2">\n',
        '                                                    {plan.published_url ? (\n',
        '                                                       <a href={plan.published_url} target="_blank" rel="noopener noreferrer" className="px-4 py-2 bg-emerald-500 text-white rounded-xl font-bold text-[9px] hover:bg-emerald-600 transition-all flex items-center gap-2 shadow-lg shadow-emerald-500/20">\n',
        '                                                          <LinkIcon size={12}/> Link Post\n',
        '                                                       </a>\n',
        '                                                    ) : editingLinkId === plan.id ? (\n',
        '                                                       <div className="flex items-center gap-2 animate-in fade-in slide-in-from-left-2">\n',
        '                                                          <input \n',
        '                                                            value={tempLinkValue}\n',
        '                                                            onChange={(e) => setTempLinkValue(e.target.value)}\n',
        '                                                            placeholder="Paste link..."\n',
        '                                                            className="h-9 w-40 rounded-lg bg-slate-50 border border-slate-200 px-3 text-[10px] font-bold focus:outline-none ring-2 ring-emerald-500/10"\n',
        '                                                          />\n',
        '                                                          <button \n',
        '                                                             onClick={() => handleUpdatePostLink(plan.id, tempLinkValue)}\n',
        '                                                             className="h-9 px-3 bg-emerald-600 text-white rounded-lg font-bold text-[9px] hover:bg-emerald-700 transition-all shrink-0"\n',
        '                                                          >\n',
        '                                                            Save\n',
        '                                                          </button>\n',
        '                                                          <button \n',
        '                                                             onClick={() => setEditingLinkId(null)}\n',
        '                                                             className="p-2 text-slate-400 hover:text-red-500 transition-all"\n',
        '                                                          >\n',
        '                                                            <X size={14}/>\n',
        '                                                          </button>\n',
        '                                                       </div>\n',
        '                                                    ) : (\n',
        '                                                       <button \n',
        '                                                         onClick={() => { setEditingLinkId(plan.id); setTempLinkValue(""); }}\n',
        '                                                         className="px-4 py-2 bg-slate-50 text-slate-400 border border-slate-100 rounded-xl font-bold text-[9px] hover:bg-slate-100 transition-all flex items-center gap-2"\n',
        '                                                       >\n',
        '                                                         <Plus size={10}/> Input Post Link\n',
        '                                                       </button>\n',
        '                                                    )}\n',
        '                                                 </div>\n',
        '                                              </td>\n',
        '                                              <td className="px-8 py-6 text-right">\n',
        '                                                 <div className="flex items-center justify-end gap-2 text-slate-300">\n',
        '                                                    {plan.status === \"uploaded\" && (\n',
        '                                                       <button \n',
        '                                                          onClick={() => openMetricsModal(plan)}\n',
        '                                                          className="p-2 hover:bg-purple-50 hover:text-purple-600 rounded-lg transition-all"\n',
        '                                                          title="Update Performance Metrics"\n',
        '                                                       >\n',
        '                                                          <BarChart2 size={16}/>\n',
        '                                                       </button>\n',
        '                                                    )}\n',
        '                                                    <button onClick={() => openEditModal(plan)} className="p-2 hover:bg-slate-100 hover:text-emerald-600 rounded-lg transition-all" title="Edit Content"><Settings size={16}/></button>\n',
        '                                                    <button onClick={() => { setTaskToDelete(plan); setIsDeleteModalOpen(true); }} className="p-2 hover:bg-red-50 hover:text-red-500 rounded-lg transition-all" title="Delete"><Trash2 size={16}/></button>\n',
        '                                                 </div>\n',
        '                                              </td>\n',
        '                                           </tr>\n',
        '                                        ))}\n',
        '                                     </tbody>\n',
        '                                  </table>\n',
        '                               </div>\n',
        '                            </Card>\n',
        '                         )}\n',
        '\n',
        '                         {contentView === "kanban" && (\n',
        '                            <div className="flex gap-8 overflow-x-auto pb-10 no-scrollbar">\n',
        '                               {Object.entries(statusConfig).map(([status, config]) => (\n',
        '                                  <div key={status} className="flex-shrink-0 w-[400px] space-y-6">\n',
        '                                     <div className="flex items-center justify-between px-4">\n',
        '                                        <div className="flex items-center gap-3">\n',
        '                                           <div className={`w-3 h-3 rounded-full ${config.dot} shadow-sm shadow-black/5`}/>\n',
        '                                           <h4 className="text-sm font-black text-[#0F172A] uppercase tracking-widest">{config.label}</h4>\n',
        '                                        </div>\n',
        '                                        <span className="text-[10px] font-black text-slate-300 bg-slate-100 px-3 py-1.5 rounded-xl">\n',
        '                                          {filteredPlans.filter(p => p.status === status).length}\n',
        '                                        </span>\n',
        '                                     </div>\n',
        '                                     \n',
        '                                     <div className="space-y-4 min-h-[400px]">\n',
        '                                        {filteredPlans.filter(p => p.status === status).map((plan) => (\n',
        '                                           <Card key={plan.id} className="p-6 bg-white border border-slate-100 shadow-lg shadow-slate-200/50 rounded-3xl space-y-4 hover:border-emerald-200 transition-all cursor-grab active:cursor-grabbing">\n',
        '                                              <div className="flex items-center justify-between">\n',
        '                                                 <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{plan.platform}</span>\n',
        '                                                 <span className="text-[9px] font-black text-emerald-600 bg-emerald-50 px-2 py-1 rounded-md">{plan.content_pillar || \"Default\"}</span>\n',
        '                                              </div>\n',
        '                                              <h5 className="text-sm font-black text-[#0F172A] leading-snug">{plan.headline || plan.title}</h5>\n',
        '                                              <div className="flex items-center justify-between pt-4 border-t border-slate-50">\n',
        '                                                  <div className="flex items-center gap-2"> \n',
        '                                                     <div className="w-5 h-5 rounded-full bg-slate-50 border border-slate-200 overflow-hidden shadow-sm"> \n',
        '                                                        <img \n',
        '                                                           src={plan.creator?.avatar_url || (currentUserProfile?.avatar_url || `https://api.dicebear.com/7.x/initials/svg?seed=${plan.creator?.full_name || (currentUserProfile?.full_name || \"Main Authority\")}`)} \n',
        '                                                           className="w-full h-full object-contain p-0.5" \n',
        '                                                           alt="Creator" \n',
        '                                                        /> \n',
        '                                                     </div> \n',
        '                                                     <span className="text-[10px] font-bold text-slate-500 italic">{plan.creator?.full_name || (currentUserProfile?.full_name || \"Main Authority\")}</span> \n',
        '                                                  </div>\n',
        '                                                 <span className="text-[9px] font-black text-slate-300 uppercase">{plan.due_date ? new Date(plan.due_date).toLocaleDateString() : "-"}</span>\n',
        '                                              </div>\n',
        '                                           </Card>\n',
        '                                        ))}\n',
        '                                     </div>\n',
        '                                  </div>\n',
        '                               ))}\n',
        '                            </div>\n',
        '                         )}\n',
        '\n',
        '                         {contentView === "calendar" && (() => {\n',
        '                           const year = currentCalendarDate.getFullYear();\n',
        '                           const month = currentCalendarDate.getMonth();\n',
        '                           const daysInMonth = new Date(year, month + 1, 0).getDate();\n',
        '                           const firstDayOfMonth = new Date(year, month, 1).getDay();\n',
        '                           const days = Array.from({ length: daysInMonth }, (_, i) => i + 1);\n',
        '                           const blanks = Array.from({ length: firstDayOfMonth }, (_, i) => i);\n',
        '\n',
        '                           return (\n',
        '                             <Card className="p-10 bg-white border-none shadow-2xl shadow-slate-200/40 rounded-[44px] space-y-8 animate-in fade-in zoom-in-95 duration-500">\n',
        '                               <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 px-2">\n',
        '                                 <div className="flex items-center gap-5">\n',
        '                                   <div className="w-16 h-16 bg-emerald-50 text-emerald-600 rounded-3xl flex items-center justify-center shadow-inner">\n',
        '                                      <CalendarIcon size={32}/>\n',
        '                                   </div>\n',
        '                                   <div>\n',
        '                                     <h3 className="text-3xl font-black text-[#0F172A] tracking-tight">{monthNames[month]} {year}</h3>\n',
        '                                     <div className="flex items-center gap-2 mt-1">\n',
        '                                        <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"/>\n',
        '                                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">\n',
        '                                          {filteredPlans.filter(p => {\n',
        '                                            if (!p.due_date) return false;\n',
        '                                            const d = new Date(p.due_date);\n',
        '                                            return d.getMonth() === month && d.getFullYear() === year;\n',
        '                                          }).length} Tasks This Month\n',
        '                                        </p>\n',
        '                                     </div>\n',
        '                                   </div>\n',
        '                                 </div>\n',
        '                                 <div className="flex items-center gap-3 bg-slate-50 p-2 rounded-[24px] border border-slate-100/50">\n',
        '                                   <button \n',
        '                                     onClick={() => setCurrentCalendarDate(new Date(year, month - 1, 1))}\n',
        '                                     className="w-12 h-12 flex items-center justify-center bg-white hover:bg-emerald-50 text-slate-400 hover:text-emerald-600 rounded-2xl transition-all hover:scale-105 active:scale-95 shadow-sm"\n',
        '                                   >\n',
        '                                     <ChevronLeft size={20}/>\n',
        '                                   </button>\n',
        '                                   <button \n',
        '                                     onClick={() => setCurrentCalendarDate(new Date())}\n',
        '                                     className="px-6 py-3 bg-slate-900 text-white rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] shadow-xl shadow-slate-900/10 hover:scale-105 active:scale-95 transition-all"\n',
        '                                   >\n',
        '                                     Today\n',
        '                                   </button>\n',
        '                                   <button \n',
        '                                     onClick={() => setCurrentCalendarDate(new Date(year, month + 1, 1))}\n',
        '                                     className="w-12 h-12 flex items-center justify-center bg-white hover:bg-emerald-50 text-slate-400 hover:text-emerald-600 rounded-2xl transition-all hover:scale-105 active:scale-95 shadow-sm"\n',
        '                                   >\n',
        '                                     <ChevronRight size={20}/>\n',
        '                                   </button>\n',
        '                                 </div>\n',
        '                               </div>\n',
        '\n',
        '                               <div className="grid grid-cols-7 gap-3">\n',
        '                                  {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(day => (\n',
        '                                     <div key={day} className="py-4 text-center text-[10px] font-black uppercase text-slate-300 tracking-[0.4em]">{day}</div>\n',
        '                                  ))}\n',
        '                                  {blanks.map(b => (\n',
        '                                     <div key={`blank-${b}`} className="min-h-[160px] rounded-[32px] bg-slate-50/20 border border-slate-50/30"></div>\n',
        '                                  ))}\n',
        '                                  {days.map(day => {\n',
        '                                     const plansOnThisDay = filteredPlans.filter(p => {\n',
        '                                        if (!p.due_date) return false;\n',
        '                                        const d = new Date(p.due_date);\n',
        '                                        return d.getDate() === day && d.getMonth() === month && d.getFullYear() === year;\n',
        '                                     });\n',
        '                                     const isToday = new Date().toDateString() === new Date(year, month, day).toDateString();\n',
        '\n',
        '                                     return (\n',
        '                                        <div key={day} className={`min-h-[160px] p-4 rounded-[32px] border transition-all group ${isToday ? "bg-emerald-50/30 border-emerald-100" : "border-slate-100/50 hover:bg-slate-50"}`}>\n',
        '                                           <div className="flex items-center justify-between mb-2">\n',
        '                                             <span className={`text-xs font-black ${isToday ? "w-8 h-8 rounded-full bg-emerald-600 text-white flex items-center justify-center shadow-lg shadow-emerald-500/20" : "text-slate-400"}`}>{day}</span>\n',
        '                                           </div>\n',
        '                                           <div className="space-y-2">\n',
        '                                              {plansOnThisDay.map(plan => (\n',
        '                                                <div key={plan.id} onClick={() => openEditModal(plan)} className="p-2 bg-white rounded-xl border border-slate-50 shadow-sm cursor-pointer hover:border-emerald-500 transition-all">\n',
        '                                                   <p className="text-[9px] font-black text-[#0F172A] line-clamp-1 truncate">{plan.headline || plan.title}</p>\n',
        '                                                </div>\n',
        '                                              ))}\n',
        '                                              {plansOnThisDay.length === 0 && (\n',
        '                                                <div className="opacity-0 group-hover:opacity-100 transition-opacity bg-slate-50/50 rounded-2xl p-3 flex items-center justify-center border border-dashed border-slate-200">\n',
        '                                                   <Plus size={12} className="text-slate-300"/>\n',
        '                                                </div>\n',
        '                                              )}\n',
        '                                           </div>\n',
        '                                        </div>\n',
        '                                     );\n',
        '                                  })}\n',
        '                               </div>\n',
        '                             </Card>\n',
        '                           );\n',
        '                         })()}\n',
        '                       </>\n',
        '                    );\n',
        '                 })()}\n',
        '\n',
        '                 {contentPlans.length === 0 && (\n',
        '                    <div className="py-40 text-center space-y-6 bg-white rounded-[44px] border border-slate-50 shadow-sm">\n',
        '                       <Layers size={60} className="mx-auto text-slate-100"/>\n',
        '                       <div className="space-y-2">\n',
        '                          <h3 className="text-xl font-black text-[#0F172A]">Belum Ada Antrean Konten</h3>\n',
        '                          <p className="text-slate-400 text-sm font-medium max-w-sm mx-auto italic">Mulai kolaborasi dengan menambahkan tugas konten pertama tim Anda.</p>\n',
        '                       </div>\n',
        '                    </div>\n',
        '                 )}\n',
        '              </div>\n',
        '           )}\n'
    ]
    
    lines[content_line_idx:meetings_start] = new_active_tab_content

with open(sys.argv[1], 'w') as f:
    f.writelines(lines)
